### ISSUE TITLE
Mod doesnt detect VLC on linux

### ISSUE THREAD

**Issue by WX580** [WaterMediaTeam/watermedia#67] opened 2024-05-01 02:31 UTC
Upon launching the game i get a warning in the logs that VLC is not preinstalled by the mod and that it was unable to find VLC on my system even though it is installed my guess is its checking windows directories.
I use the KDE spin of Fedora 40 and the flatpak of the prism launcher
Ive tried using both the flatpak and fedora package of VLC

**Comment by SrRapero720** [comment] 2024-05-01 04:37
I transferred your issue to watermedia (because is the responsable mod of VLC loading)

**Comment by SrRapero720** [comment] 2024-05-01 04:39
# 🗃️ I NEED YOUR LOGS TO DIAGNOSE
Your latest.log file is placed in your ``.minecraft/logs`` folder (instance folder), pickup the file and upload it into any website below. 
If your game crashes please also append the crash report in the ``.minecraft/crash-report`` folder.
Paste it here so i can help you more easier

# 🖥️ PASTE PAGES
- **Github (100MB)**: https://gist.github.com/
- **MCLogs (10MB)**: https://mclo.gs/
- **PasteGG (15MB)**: https://paste.gg/
- **PasteEE (1MB)**: https://paste.ee/
- **HasteBin (400kB)**: https://hastebin.com/
- **CentOS (1MB)**: https://paste.centos.org/

**Comment by WX580** [comment] 2024-05-01 11:06
https://gist.github.com/WX580/27fa5bb54c2f8c236447f4bd7eb4d007

The errors are on lines 57 and 119

**Comment by SrRapero720** [comment] 2024-05-01 17:19
please update watermedia

**Comment by WX580** [comment] 2024-05-01 18:56
![image](https://github.com/SrRapero720/watermedia/assets/119598169/9e1a522c-cbf1-4947-b191-526aa7994e32)
upon updating watermedia and waterframes i receive a error every time i open the game about loading water frames along with the following lines in my log file
https://gist.github.com/WX580/1c3627a845cf62f5ea70299f5091e5ad
on mc version 1.18.2

**Comment by SrRapero720** [comment] 2024-05-01 20:39
error 1 indicates VLC is not installed
please send me where flatpack places the VLC binaries

error 2 indicates a class is missing on creativecore, which mean you havenot installed the right version
read the 2.0.0 changelog of waterframes to see what you need to install

**Comment by WX580** [comment] 2024-05-01 21:01
sorry about accidentally closing it 
/home/wx580/.var/app/org.videolan.VLC/
thats where vlc should be stored or the data for it atleast cant seem to find the executable

**Comment by Jaskowicz1** [comment] 2024-06-04 20:41
Thought I'd jump in on this issue too as I'd figured out the issue from #79, you can't have prism launcher from Flatpak as the sandbox prevents it from seeing these files.

**Comment by SrRapero720** [comment] 2024-06-25 03:57
this issue was confirmed was a flatpak installation
flatpak will remain unsupported, please install Minecraft (And VLC) using other alternatives or doing manual installation, or just use ubuntu + apt-get

**Closed as not planned by SrRapero720** 2024-06-25 03:57 UTC
Labels: ⏳ Delayed, 🟤 Shameful Issue
